const scriptHashes = [
  "'sha256-V7ZX04Z18puN/+NFTXkoLWCRNlyYP9sNLaM3JuZGbbg='",
  "'sha256-fGegghFk3+BZLENLENjuryQ4DcON6/k/RtpHi+kUkXg='",
  "'sha256-UhWJJUIQEYQy05tDlXNGby1oPZJQEbkm4aT3CaDez3A='",
  "'sha256-oZVujOaMFZjMEvHWesZOkg60VCQuobVehfXgcdYfQo0='",
  "'sha256-GZp2MKMT/9EgsAS7y9zrtykhD42ylrbWfLYSe5mcRU4='",
  "'sha256-SBnenP8axkYxVEg7Rv0yKYMbpUudEUXk17mPyAjDFKA='",
  "'sha256-QKiVxVeaD8S2Z8S4ascTX3ygxTQAiW8/m4S0u8AisYE='",
  "'sha256-Ld1ye3yqwNZGebreMgvHnrPMAo0p6CWBj3jUnHFTPTk='",
  "'sha256-1EMyjoanz0WAGY/uoK7B2hWU3BFZcQ4bm9brKL1ptM4='",
  "'sha256-Uk6Tlfo9V3Mrbt+Ykg/6u4HuT1VWOCgBYJRO74Ne4uk='",
  "'sha256-RL6Q5G/YMEVuMoRekD0O1pM/G5NvwE/2w+KF9pxmuLY='",
  "'sha256-YIJzMk6NWu3GLXfznIJ9HuXg4sunkNtZkXw8Y/0US4E='",
  "'sha256-f66mh0vglU0RJ0jPzrwq/5GeQxLrktm3HOxJD7HdjFM='",
  "'sha256-/7402/hyIoX7TkTlu6NrD4/oxQTUfQdLIQpWPdI/t3A='",
  "'sha256-MUeI/o4a/JYALJY2cNSh40FFa8qxURaU96LBFH2Q2s4='",
  "'sha256-KeOzFzHCZ1AYMopf2Fa2eVr7KU6iu9eVtlCslV0EzWc='",
  "'sha256-aHlg1rTlKaP8qoz3Nok4KCZxyRYp+AHn0lYxcn/avSs='",
  "'sha256-Haq7dB84s90wLMJeaMrbClfPkKmP2NgLnhg8NbgIjPs='",
  "'sha256-zQYLdNgMjU8kUDNuNN9gJAjJdQmV2uNzjDJYhf+mCv0='",
  "'sha256-xxvIRTQJoylqEyitk+q6RK5ZsZWdhF5XzV6m21NVo0c='",
  "'sha256-NRujCAvN4HcWuzeij8v1CxnGSykkUAlFjLFjd6o0hOQ='",
  "'sha256-g70hWP7cReYpGcwUJVps37idxZLnXvUqd3uA9h4oySI='",
  "'sha256-S0xg6c4AOMAEgz+fwlrt/jq0anOtJ9PswICbxFfKtxY='",
  "'sha256-ts0eEEaNzYbyyXxdJkvLzZe1Yy9Dk1VVLu9emLZGQiM='",
  "'sha256-x3ndY+az7GyetBSeND03+PM5YJCwg8nFxmRn/I1vM4o='",
  "'sha256-njZwzYuFs6N3Ii/CJoEl3ls0kj/ObaynOXs9lUPBZA4='",
  "'sha256-Z9NqYwd0V1INI7M0hEpnkwzBu3FNMic+Mv0mlfaXMvw='",
  "'sha256-vl3hIY6HT4uA9QXn5a0v3rhuajlxbnZmeCN+6ii/Q2Q='",
  "'sha256-oDW+UDmxBtctb6VKXbcEt3tD3baORORHIz71bTuD+SI='",
  "'sha256-/Wg8pjyJkdcK2b97qwfsGJ54O15Gq/R5gmcMRdBOnuM='",
  "'sha256-h3QFdTEx9nod/h7huGKltp7LiyG4V3Wbn86adMPe2II='",
];

const securityHeaders = [
  {
    key: 'Strict-Transport-Security',
    value: 'max-age=63072000; includeSubDomains; preload',
  },
  {
    key: 'X-Content-Type-Options',
    value: 'nosniff',
  },
  {
    key: 'Referrer-Policy',
    value: 'strict-origin-when-cross-origin',
  },
  {
    key: 'Permissions-Policy',
    value: 'camera=(), microphone=(), geolocation=(), payment=(), usb=(), browsing-topics=()',
  },
  {
    key: 'X-Frame-Options',
    value: 'DENY',
  },
  {
    key: 'Content-Security-Policy',
    value: [
      "default-src 'self'",
      "base-uri 'self'",
      "object-src 'none'",
      "frame-ancestors 'none'",
      "img-src 'self' data: blob: https:",
      "font-src 'self' data:",
      "style-src 'self' 'unsafe-inline'",
      ["script-src 'self'", ...scriptHashes, "https://www.googletagmanager.com", "https://www.google-analytics.com", "https://www.googleadservices.com", "https://googleads.g.doubleclick.net", "https://challenges.cloudflare.com"].join(' '),
      "connect-src 'self' https://www.google-analytics.com https://region1.google-analytics.com https://www.googletagmanager.com https://www.googleadservices.com https://googleads.g.doubleclick.net https://challenges.cloudflare.com",
      "frame-src 'self' https://www.googletagmanager.com https://challenges.cloudflare.com https://www.google.com https://maps.google.com https://www.youtube.com",
      "form-action 'self'",
      "upgrade-insecure-requests",
    ].join('; '),
  },
];

/** @type {import('next').NextConfig} */
const nextConfig = {
  async headers() {
    return [
      {
        source: '/:path*',
        headers: securityHeaders,
      },
    ];
  },
  async redirects() {
    return [
      {
        source: '/:path*',
        has: [{ type: 'host', value: 'www.rozanabi.com' }],
        destination: 'https://rozanabi.com/:path*',
        permanent: true,
      },
      { source: '/about.html', destination: '/about', permanent: true },
      { source: '/contact.html', destination: '/contact', permanent: true },
      { source: '/cookie-policy.html', destination: '/cookie-policy', permanent: true },
      { source: '/demo-afrooz-mini-website.html', destination: '/demo-afrooz-mini-website', permanent: true },
      { source: '/demo-afrooz-product-afrouz-signature-edp.html', destination: '/demo-afrooz-product-afrouz-signature-edp', permanent: true },
      { source: '/demo-afrooz-product-luxury-perfumes.html', destination: '/demo-afrooz-product-luxury-perfumes', permanent: true },
      { source: '/demo-afrooz-product-natural-attars.html', destination: '/demo-afrooz-product-natural-attars', permanent: true },
      { source: '/demo-afrooz-product-oud-collection.html', destination: '/demo-afrooz-product-oud-collection', permanent: true },
      { source: '/demo-afrooz-product-musk-collection.html', destination: '/demo-afrooz-product-musk-collection', permanent: true },
      { source: '/demo-afrooz-product-perfume-gift-sets.html', destination: '/demo-afrooz-product-perfume-gift-sets', permanent: true },
      { source: '/demo-afrooz-product-best-sellers.html', destination: '/demo-afrooz-product-best-sellers', permanent: true },
      { source: '/demo-afrooz-product-mini-and-travel-scents.html', destination: '/demo-afrooz-product-mini-and-travel-scents', permanent: true },
      { source: '/demo-mayas-collection-mini-website.html', destination: '/demo-mayas-collection-mini-website', permanent: true },
      { source: '/demo-mayas-collection-mini-website-tr.html', destination: '/demo-mayas-collection-mini-website-tr', permanent: true },
      { source: '/demo-eventona-mini-website.html', destination: '/demo-eventona-mini-website', permanent: true },
      { source: '/demo-dokon-collective-mini-website.html', destination: '/demo-dokon-collective-mini-website', permanent: true },
      { source: '/demo-mens-barbershop-mini-website.html', destination: '/demo-mens-barbershop-mini-website', permanent: true },
      { source: '/demo-ladies-salon-mini-website.html', destination: '/demo-ladies-salon-mini-website', permanent: true },
      { source: '/demo-beauty-clinic-landing.html', destination: '/demo-beauty-clinic-landing', permanent: true },
      { source: '/demo-cafe-landing.html', destination: '/demo-cafe-landing', permanent: true },
      { source: '/demo-dental-clinic-landing.html', destination: '/demo-dental-clinic-landing', permanent: true },
      { source: '/demo-real-estate-landing.html', destination: '/demo-real-estate-landing', permanent: true },
      { source: '/demo-service-company-landing.html', destination: '/demo-service-company-landing', permanent: true },
      { source: '/demo-training-institute-landing.html', destination: '/demo-training-institute-landing', permanent: true },
      { source: '/faq.html', destination: '/faq', permanent: true },
      { source: '/index.html', destination: '/', permanent: true },
      { source: '/industries.html', destination: '/industries', permanent: true },
      { source: '/insight-ai-models-chatbots.html', destination: '/insight-ai-models-chatbots', permanent: true },
      { source: '/insight-ai-workflow-automation.html', destination: '/insight-ai-workflow-automation', permanent: true },
      { source: '/insight-business-analysis-requirements.html', destination: '/insight-business-analysis-requirements', permanent: true },
      { source: '/insight-content-keyword-strategy.html', destination: '/insight-content-keyword-strategy', permanent: true },
      { source: '/insight-data-governance-gcc.html', destination: '/insight-data-governance-gcc', permanent: true },
      { source: '/insight-digital-growth-campaigns.html', destination: '/insight-digital-growth-campaigns', permanent: true },
      { source: '/insight-erp-readiness.html', destination: '/insight-erp-readiness', permanent: true },
      { source: '/insight-seo-aeo-geo.html', destination: '/insight-seo-aeo-geo', permanent: true },
      { source: '/insight-seo-measurement-stack.html', destination: '/insight-seo-measurement-stack', permanent: true },
      { source: '/insight-seo-ready-web-design.html', destination: '/insight-seo-ready-web-design', permanent: true },
      { source: '/insights.html', destination: '/insights', permanent: true },
      { source: '/landing-page-oman.html', destination: '/landing-page-oman', permanent: true },
      { source: '/privacy-policy.html', destination: '/privacy-policy', permanent: true },
      { source: '/seo-dashboard-demo.html', destination: '/seo-dashboard-demo', permanent: true },
      { source: '/services.html', destination: '/services', permanent: true },
      { source: '/terms-conditions.html', destination: '/terms-conditions', permanent: true },
      { source: '/thank-you.html', destination: '/thank-you', permanent: true },
      { source: '/use-case-ai-marketing-workflow.html', destination: '/use-case-ai-marketing-workflow', permanent: true },
      { source: '/use-case-dokon-collective-website.html', destination: '/use-case-dokon-collective-website', permanent: true },
      { source: '/use-case-market-competitor-analysis.html', destination: '/use-case-market-competitor-analysis', permanent: true },
      { source: '/use-case-mayas-collection-instagram-growth.html', destination: '/use-case-mayas-collection-instagram-growth', permanent: true },
      { source: '/use-case-seo-ready-website.html', destination: '/use-case-seo-ready-website', permanent: true },
      { source: '/use-cases.html', destination: '/use-cases', permanent: true },
    ];
  },
  async rewrites() {
    return {
      beforeFiles: [
        { source: '/about', destination: '/about.html' },
        { source: '/contact', destination: '/contact.html' },
        { source: '/cookie-policy', destination: '/cookie-policy.html' },
        { source: '/demo-afrooz-mini-website', destination: '/demo-afrooz-mini-website.html' },
        { source: '/demo-afrooz-product-afrouz-signature-edp', destination: '/demo-afrooz-product-afrouz-signature-edp.html' },
        { source: '/demo-afrooz-product-luxury-perfumes', destination: '/demo-afrooz-product-luxury-perfumes.html' },
        { source: '/demo-afrooz-product-natural-attars', destination: '/demo-afrooz-product-natural-attars.html' },
        { source: '/demo-afrooz-product-oud-collection', destination: '/demo-afrooz-product-oud-collection.html' },
        { source: '/demo-afrooz-product-musk-collection', destination: '/demo-afrooz-product-musk-collection.html' },
        { source: '/demo-afrooz-product-perfume-gift-sets', destination: '/demo-afrooz-product-perfume-gift-sets.html' },
        { source: '/demo-afrooz-product-best-sellers', destination: '/demo-afrooz-product-best-sellers.html' },
        { source: '/demo-afrooz-product-mini-and-travel-scents', destination: '/demo-afrooz-product-mini-and-travel-scents.html' },
        { source: '/demo-mayas-collection-mini-website', destination: '/demo-mayas-collection-mini-website.html' },
        { source: '/demo-mayas-collection-mini-website-tr', destination: '/demo-mayas-collection-mini-website-tr.html' },
        { source: '/demo-eventona-mini-website', destination: '/demo-eventona-mini-website.html' },
        { source: '/demo-dokon-collective-mini-website', destination: '/demo-dokon-collective-mini-website.html' },
        { source: '/demo-mens-barbershop-mini-website', destination: '/demo-mens-barbershop-mini-website.html' },
        { source: '/demo-ladies-salon-mini-website', destination: '/demo-ladies-salon-mini-website.html' },
        { source: '/demo-beauty-clinic-landing', destination: '/demo-beauty-clinic-landing.html' },
        { source: '/demo-cafe-landing', destination: '/demo-cafe-landing.html' },
        { source: '/demo-dental-clinic-landing', destination: '/demo-dental-clinic-landing.html' },
        { source: '/demo-real-estate-landing', destination: '/demo-real-estate-landing.html' },
        { source: '/demo-service-company-landing', destination: '/demo-service-company-landing.html' },
        { source: '/demo-training-institute-landing', destination: '/demo-training-institute-landing.html' },
        { source: '/faq', destination: '/faq.html' },
        { source: '/', destination: '/index.html' },
        { source: '/industries', destination: '/industries.html' },
        { source: '/insight-ai-models-chatbots', destination: '/insight-ai-models-chatbots.html' },
        { source: '/insight-ai-workflow-automation', destination: '/insight-ai-workflow-automation.html' },
        { source: '/insight-business-analysis-requirements', destination: '/insight-business-analysis-requirements.html' },
        { source: '/insight-content-keyword-strategy', destination: '/insight-content-keyword-strategy.html' },
        { source: '/insight-data-governance-gcc', destination: '/insight-data-governance-gcc.html' },
        { source: '/insight-digital-growth-campaigns', destination: '/insight-digital-growth-campaigns.html' },
        { source: '/insight-erp-readiness', destination: '/insight-erp-readiness.html' },
        { source: '/insight-seo-aeo-geo', destination: '/insight-seo-aeo-geo.html' },
        { source: '/insight-seo-measurement-stack', destination: '/insight-seo-measurement-stack.html' },
        { source: '/insight-seo-ready-web-design', destination: '/insight-seo-ready-web-design.html' },
        { source: '/insights', destination: '/insights.html' },
        { source: '/landing-page-oman', destination: '/landing-page-oman.html' },
        { source: '/privacy-policy', destination: '/privacy-policy.html' },
        { source: '/seo-dashboard-demo', destination: '/seo-dashboard-demo.html' },
        { source: '/services', destination: '/services.html' },
        { source: '/terms-conditions', destination: '/terms-conditions.html' },
        { source: '/thank-you', destination: '/thank-you.html' },
        { source: '/use-case-ai-marketing-workflow', destination: '/use-case-ai-marketing-workflow.html' },
        { source: '/use-case-dokon-collective-website', destination: '/use-case-dokon-collective-website.html' },
        { source: '/use-case-market-competitor-analysis', destination: '/use-case-market-competitor-analysis.html' },
        { source: '/use-case-mayas-collection-instagram-growth', destination: '/use-case-mayas-collection-instagram-growth.html' },
        { source: '/use-case-seo-ready-website', destination: '/use-case-seo-ready-website.html' },
        { source: '/use-cases', destination: '/use-cases.html' },
      ],
    };
  },
};

export default nextConfig;
